package paivakirja;
// Generated by ComTest BEGIN
import paivakirja.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.14 10:54:18 // Generated by ComTest
 *
 */
public class HarjoitusTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi102 */
  @Test
  public void testRekisteroi102() {    // Harjoitus: 102
    Harjoitus harj1 = new Harjoitus(); 
    assertEquals("From: Harjoitus line: 105", 0, harj1.getIdNumero()); 
    harj1.rekisteroi(); 
    Harjoitus harj2 = new Harjoitus(); 
    harj2.rekisteroi(); 
    int a = harj1.getIdNumero(); 
    int b = harj2.getIdNumero(); 
    assertEquals("From: Harjoitus line: 111", 1, b - a); 
    harj1.asetaKentat("  3|1.1.2013|sointu|test|testi|110  "); 
    assertEquals("From: Harjoitus line: 113", true, harj1.toString().equals("3|1.1.2013|sointu|test|testi|110")); 
  } // Generated by ComTest END
}