package paivakirja;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.14 13:30:03 // Generated by ComTest
 *
 */
public class HarjoituksetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa34 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa34() throws SailoException {    // Harjoitukset: 34
    Harjoitukset harjoitukset = new Harjoitukset(); 
    Harjoitus harj1 = new Harjoitus(); 
    Harjoitus harj2 = new Harjoitus(); 
    harjoitukset.lisaa(harj1); 
    int a = harjoitukset.getLukumaara(); 
    harjoitukset.lisaa(harj2); 
    int b =  harjoitukset.getLukumaara(); 
    assertEquals("From: Harjoitukset line: 43", 1, b - a); 
    assertEquals("From: Harjoitukset line: 44", harj1, harjoitukset.anna(0)); 
    assertEquals("From: Harjoitukset line: 45", harj2, harjoitukset.anna(1)); 
    try {
    assertEquals("From: Harjoitukset line: 46", harj1, harjoitukset.anna(4)); 
    fail("Harjoitukset: 46 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    harjoitukset.lisaa(harj2); 
    harjoitukset.lisaa(harj2); 
    harjoitukset.lisaa(harj2); 
    harjoitukset.lisaa(harj2); 
    harjoitukset.lisaa(harj2); 
    harjoitukset.lisaa(harj2); 
    harjoitukset.lisaa(harj2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHaeHarjoitukset133 
   * @throws SailoException when error
   */
  @Test
  public void testHaeHarjoitukset133() throws SailoException {    // Harjoitukset: 133
    Harjoitukset harjtesti = new Harjoitukset(); 
    Harjoitus harj1t = new Harjoitus(); 
    Harjoitus harj2t = new Harjoitus(); 
    harj1t.vastaaEkaHarj(); 
    harj2t.vastaaEkaHarj(); 
    String hakemisto = "pvktesti"; 
    String tnimi = hakemisto+"/harjoitukset"; 
    File dir = new File(hakemisto); 
    File tiedosto = new File(tnimi+".dat"); 
    dir.mkdir(); 
    tiedosto.delete(); 
    try {
    harjtesti.haeHarjoitukset(tnimi); 
    fail("Harjoitukset: 147 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    harjtesti.lisaa(harj1t); 
    harjtesti.lisaa(harj2t); 
    harjtesti.tallenna(); 
    harjtesti = new Harjoitukset(); 
    harjtesti.haeHarjoitukset(tnimi); 
    assertEquals("From: Harjoitukset line: 153", true, harjtesti.anna(0).toString().equals(harj1t.toString())); 
    assertEquals("From: Harjoitukset line: 154", true, harjtesti.anna(1).toString().equals(harj2t.toString())); 
    assertEquals("From: Harjoitukset line: 155", true, tiedosto.delete()); 
    assertEquals("From: Harjoitukset line: 156", true, dir.delete()); 
  } // Generated by ComTest END
}