package paivakirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.14 13:36:15 // Generated by ComTest
 *
 */
public class TranskriptioTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi143 */
  @Test
  public void testRekisteroi143() {    // Transkriptio: 143
    Transkriptio badmama1 = new Transkriptio(); 
    assertEquals("From: Transkriptio line: 145", 0, badmama1.getIdNumero()); 
    badmama1.rekisteroi(); 
    Transkriptio badmama2 = new Transkriptio(); 
    badmama2 .rekisteroi(); 
    int a = badmama1.getIdNumero(); 
    int b = badmama2 .getIdNumero(); 
    assertEquals("From: Transkriptio line: 151", 1, b - a); 
    badmama1.asetaKentat("  4|Eye of the Tiger|Rocky  "); 
    assertEquals("From: Transkriptio line: 153", true, badmama1.toString().equals("4|Eye of the Tiger|Rocky")); 
  } // Generated by ComTest END
}