package paivakirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import paivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.14 13:39:25 // Generated by ComTest
 *
 */
public class TransliitosTest {



  // Generated by ComTest BEGIN
  /** testAsetaKentat75 */
  @Test
  public void testAsetaKentat75() {    // Transliitos: 75
    Transliitos liitos1 = new Transliitos(); 
    liitos1.asetaKentat("1|2"); 
    liitos1.toString().equals("1|2"); 
  } // Generated by ComTest END
}