package kanta;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.03.11 12:42:04 // Generated by ComTest
 *
 */
public class IntTest {



  // Generated by ComTest BEGIN
  /** testInt17 */
  @Test
  public void testInt17() {    // Int: 17
    Int integer = new Int(2); 
    assertEquals("From: Int line: 19", " 2", integer.toString()); 
  } // Generated by ComTest END
}